bookReview/BookProject/models.py
from BookProject import db, login
from flask_login import UserMixin
from datetime import datetime

@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class Review(db.Model):
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), primary_key=True)
    book_id = db.Column(db.Integer, db.ForeignKey("book.id"), primary_key=True)
    date = db.Column( db.DateTime, default=datetime.utcnow)
    rating = db.Column( db.Integer, nullable=True)
    comment = db.Column(db.String(500), nullable=True)
    user = db.relationship('User', backref="reviews", lazy= True)
    book = db.relationship('Book', backref="reviews", lazy= True)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(40), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    picture = db.Column(db.String(100), default="default.png")
    books= db.relationship('Book',secondary="review", backref="users", lazy=True)

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    isbn = db.Column(db.String(100), unique=True, nullable=False)
    title = db.Column(db.String(100),nullable=False)
    author = db.Column(db.String(40), nullable=False)
    year =db.Column(db.Integer, nullable=False)

bookReview/BookProject/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from BookProject.config import Config



bcrypt = Bcrypt()
login = LoginManager()
db = SQLAlchemy()
login.login_view="user.login"

def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(config)
    bcrypt.init_app(app)
    login.init_app(app)
    db.init_app(app)

    from BookProject.main.routes import main
    from BookProject.errors.handlers import error
    from BookProject.book.routes import books
    from BookProject.user.routes import user
    from BookProject.api.routes import apis

    app.register_blueprint(main)
    app.register_blueprint(error)
    app.register_blueprint(books)
    app.register_blueprint(user)
    app.register_blueprint(apis)

    return app

bookReview/BookProject/api/routes.py
from flask import Blueprint, render_template, redirect, flash, jsonify
from BookProject import db
from BookProject.config import dic
from BookProject.models import Book, Review
from sqlalchemy import func

apis=Blueprint('apis', __name__)
 
@apis.route('/api/<string:isbn>', methods=["GET"])
def getBook(isbn): 
    book = Book.query.filter_by(isbn=isbn).first()
    if book:
        count = Review.query.filter_by(book_id=book.id).count()
        average = 0
        if count!=0 :
            average = round(float(db.session.query(func.avg(Review.rating)).filter(Review.book_id == book.id).first()[0]) , 2)
        api = {'title':book.title, 'author': book.author, 'year': book.year, 'isbn':book.isbn, 'review_count':count, 'average_score':average}
        return jsonify(api)
    else:
        return jsonify({'status_code':404,'error':'No matching ISBN'})

bookReview/BookProject/book/routes.py
from flask import Blueprint, render_template, redirect, flash
from BookProject.book.form import Reviews
from flask_login import current_user, login_required
from BookProject import db
from BookProject.config import dic
from BookProject.models import Book, Review
import requests


books=Blueprint('books', __name__)

@books.route('/book/<int:id>', methods=['GET', 'POST'])
@login_required
def book(id):
    book = Book.query.get_or_404(id)
    goodReads = 'Not available from GoodReads'
    res = requests.get("https://www.goodreads.com/book/review_counts.json", params={'key': dic['API_KEY'], 'isbns': [book.isbn]})
    if res.status_code == 200:
        data= res.json()
        goodReads = f"(The average rating: {data['books'][0]['average_rating']}, with {data['books'][0]['ratings_count']} ratings from GoodReads)"
    form = Reviews()
    if Review.query.filter(Review.user_id==current_user.id, Review.book_id==book.id).first():
        form = None
    if form and form.validate_on_submit():
        review = Review(user_id=current_user.id, book_id=id, rating= form.rating.data, comment= form.comment.data)
        db.session.add(review)
        db.session.commit()
        form = None
        flash('Thank you for your rating!',category='success')
    return render_template('book.html', book=book, title='Book Page', form = form, goodReads=goodReads)

bookReview/BookProject/main/routes.py
from flask import Blueprint, render_template, redirect, flash
from BookProject.main.form import Search
from flask_login import current_user
from BookProject import db
from BookProject.models import Book

main = Blueprint('main', __name__)

@main.route('/', methods=['GET','POST'])
def home():
    form = None
    books = None
    if current_user.is_authenticated:
        form = Search()
        if form.validate_on_submit():
            data = form.query.data
            if form.select.data=="isbn":
                books = Book.query.filter(Book.isbn.like(f'%{data}%')).all()
            elif form.select.data=="author":
                books = Book.query.filter(Book.author.like(f'%{data}%')).all()
            elif form.select.data=="title":
                books = Book.query.filter(Book.title.like(f'%{data}%')).all()
            if books==[]:
                flash('There is no matching results!', category='warning')
    return render_template('home.html', form=form, books=books)

 


bookReview/BookProject/user/routes.py
from flask import Blueprint, render_template, redirect, flash, request
from BookProject.user.form import Registration, Login
from flask_login import current_user, login_required, login_user, logout_user
from BookProject import db, bcrypt
from BookProject.models import User, Book, Review

user = Blueprint('user', __name__)

@user.route('/register',methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect('/')
    form = Registration()
    if form.validate_on_submit():
        data = User.query.filter_by(username = form.username.data).first()
        if data == None:
            hashpw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username = form.username.data, password = hashpw)
            db.session.add(user)
            db.session.commit()
            flash("Create a new account successfully!",category='success')
            return redirect('/login')
        else:
            form.username.errors.append('Username already exists in database')
    return render_template('register.html', form=form)

@user.route('/login',methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect('/')
    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user, remember=False)
                flash("Login successfully!", category='success')
                next= request.args.get('next')
                if next:
                    return redirect(next)
                else: 
                    return redirect('/')
            else:
                form.password.errors.append("Wrong password!")
        else:
            form.username.errors.append("Username does not exist!")
    return render_template('login.html', form=form)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Logout successfully!", category='success')
    return redirect('/')

bookReview/BookProject/templates/book.html
{% extends "layout.html" %}
{% block body %} 
    <h1>Book Detail</h1>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h4 class="card-title">Title: {{book.title}}</h4>
          <h6 class="card-subtitle mb-2 text-muted">Author: {{book.author}}</h6>
          <h6 class="card-subtitle mb-2 text-muted">Publication year: {{book.year}}</h6>
          <h6 class="card-subtitle mb-2 text-muted">ISBN: {{book.isbn}}</h6>
        </div>
    </div><br>
    {% if form %}
    <h1>Write your comment</h1>
    <div class="col col-lg-6">
        <form action="" method="POST">
            {{form.hidden_tag()}}
            <div class="form-group">
                {{form.rating.label(class="form-control-label")}} 
                    {% if form.rating.errors %}
                        <div class="alert alert-danger">
                            {% for error in form.rating.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                {{form.rating(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.comment.label(class="form-control-label")}} 
                    {% if form.comment.errors %}
                        <div class="alert alert-danger">
                            {% for error in form.comment.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                {{form.comment(class="form-control form-control-lg")}} 
            </div>
            {{form.submit(class="btn btn-primary")}}
        </form>
    </div>
    {% else %}
        <p class="alert alert-warning">You already reviewed this book!!</p>
    {% endif %}

    <h1>Reviews</h1>
    <span>{{goodReads}}</span>
    {% if book.reviews %}
        {% for review in book.reviews %}
        <div class="card" >
            <div class="card-body">
              <h5 class="card-title">{{review.user.username}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">Rating : {{review.rating}} ({{review.date.strftime('%m-%d-%Y')}}) </h6>
              <p class="card-text">{{review.comment}}</p>
            </div>
        </div><br>
        {% endfor %}
    {% endif %}
{% endblock %}

bookReview/BookProject/templates/home.html
{% extends "layout.html" %}
{% block body %}
    <h1>Home</h1>
    {% if current_user.is_authenticated %}
        <span>Search books by title/author/ISBN</span>
        <form action="" method="POST">
            {{form.hidden_tag()}}
            <div class ="container row justify-content-between">
                {{form.select(class="form-control col col-2")}}  
                {{form.query(class="form-control col col-7", placeholder="Search", autocomplete="off")}} 
                {{form.submit(class="btn btn-outline-success col col-2")}} <br>
            </div>
        </form>
        {% if books %}
            <h1>Results</h1>
            <ul class="list-group list-group-flush">
                {% for book in books %}
                    <li class="list-group-item">
                        <a href="{{url_for('books.book', id=book.id)}}" class="nav-item nav-link">{{book.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% else %}
    <h6 class="mb-2 text-muted">Please login or register to review a book!</h6>
    {% endif %}

{% endblock %}

bookReview/BookProject/templates/layout.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
        {% if title %}
            <title>{{title}}</title>
        {% else %}
            <title>Default</title>
        {% endif %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Books</a>
                <div class="collapse navbar-collapse" id="navbarToggle">
                  <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="/">Home</a>
                  </div>
                  <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a href="/logout" class="nav-item nav-link">Log out</a>
                    {% else %}
                      <a class="nav-item nav-link" href="/login">Login</a>
                      <a class="nav-item nav-link" href="/register">Register</a>
                    {% endif %}
                  </div>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-12">  
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class='alert alert-{{category}}'>{{message}}</div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        </div>
        
        <div class="container">
            {% block body %}{% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

bookReview/BookProject/templates/login.html
{% extends "layout.html" %}
{% block body %}
    <div class="col col-lg-6"> 
        <form action="" method="POST">
                {{form.hidden_tag()}}
                <h1>Login</h1>
                <div class="form-group"> 
                    {{form.username.label(class="form-control-label")}}
                    {% if form.username.errors %}
                        <div class="alert alert-danger">
                            {% for error in form.username.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {{form.username(class="form-control form-control-lg")}}
                </div>
                <div class="form-group"> 
                    {{form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        <div class="alert alert-danger">
                            {% for error in form.password.errors %}
                                <span>{{error}}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {{form.password(class="form-control form-control-lg")}}
                </div>
                {{form.submit(class="btn btn-primary")}}
        </form>
    </div>
    
{% endblock %}

bookReview/BookProject/templates/register.html
{% extends "layout.html" %}
{% block body %}
    <div class="col col-lg-6 " >
        <form action="" method="POST">
            {{form.hidden_tag()}}
            <h1>Registration</h1>
            <div class="form-group"> 
                {{form.username.label(class="form-control-label")}}
                {% if form.username.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.username.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                {{form.username(class="form-control form-control-lg")}} 
            </div>
            <div class="form-group"> 
                {{form.password.label(class="form-control-label")}} 
                {% if form.password.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                {{form.password(class="form-control form-control-lg")}} 
            </div>
            <div class="form-group"> 
                {{form.confirm.label(class="form-control-label")}} 
                {% if form.confirm.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.confirm.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                {{form.confirm(class="form-control form-control-lg")}} 
            </div>
            {{form.submit(class="btn btn-primary")}}
            
        </form>
    </div>

{% endblock %}